name: Coverage Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  applications:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate Coverage Report
        run: mvn clean verify
      - name: Archive Jacoco reports
        uses: actions/upload-artifact@v2.2.4
        with:
          name: jacoco-reports
          path: test-coverage/target/site/jacoco-aggregate