name: Coverage Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  applications:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate Coverage Report
        run: mvn -B test
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true